name: getx_mvvm
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  pin_code_text_field: ^1.8.0
  chatbox: ^0.0.4
  chat_bubbles: ^1.6.0
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  dio: ^5.7.0
  flutter_otp_text_field: ^1.2.0
#  fluttertoast: ^8.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins.ttf

     - family: Inter
       fonts:
         - asset: assets/fonts/Inter1.ttf


